import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { CookiesProvider } from 'next-client-cookies/server';
import { Toaster } from '@/components/ui/toaster';
import { ToasterSonner } from '@/components/ui/sonner';
import Header from '@/components/header/Header';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={inter.className}>
				<CookiesProvider>
					<ThemeProvider attribute='class' defaultTheme='system' enableSystem>
						<Header />
						{children}
						<Toaster />
						<ToasterSonner richColors />
					</ThemeProvider>
				</CookiesProvider>
			</body>
		</html>
	);
}
